language: go
go:
 - 1.9
 - "1.10"

before_install:
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls

script:
 - go test -race -v -coverprofile=coverage.txt -covermode=atomic

after_success:
 - bash <(curl -s https://codecov.io/bash)
